import bagde_logo from "../images/coralbay-white-badge-logo.png"
import tshirt_red from "../images/fashion-img(1).png"
import tshirt_blue from "../images/fashion-img(1)(2).png"
import tshirt_black from "../images/fashion-img(1)(3).png"
import tshirt_yellow from "../images/fashion-img(1)(4).png"
import shoes_yellow from "../images/fashion-img(2).png"
import shoes_orange from "../images/fashion-img(2)(2).png"
import shoes_black from "../images/fashion-img(2)(4).png"
import shoes_blue from "../images/fashion-img(2)(3).png"
import stool_black from "../images/fashion-img(3).png"
import stool_green from "../images/fashion-img(3)(2).png"
import stool_white from "../images/fashion-img(3)(4).png"
import stool_grey from "../images/fashion-img(3)(3).png"
import shoes2_black from "../images/fashion-img(4)(3).png"
import shoes2_grey from "../images/fashion-img(4)(2).png"
import shoes2_yellow from "../images/fashion-img(4).png"
import shoes2_orange from "../images/fashion-img(4)(4).png"
import stockmart_black from "../images/fashion-img(5).png"
import stockmart_green from "../images/fashion-img(5)(2).png"
import stockmart_blue from "../images/fashion-img(5)(3).png"
import stockmart_brown from "../images/fashion-img(5)(4).png"
import digital_1 from "../images/fashion-img(6).png"
import digital_2 from "../images/fashion-img(6)(2).png"
import digital_3 from "../images/fashion-img(6)(3).png"
import bunny_toy_1 from "../images/fashion-img(7).png"
import bunny_toy_2 from "../images/fashion-img(7)(2).png"
import bunny_toy_3 from "../images/fashion-img(7)(3).png"
import bunny_toy_4 from "../images/fashion-img(7)(4).png"
import battery_1 from "../images/fashion-img(8).png"
import battery_2 from "../images/fashion-img(8)(2).png"
import battery_3 from "../images/fashion-img(8)(3).png"
import battery_4 from "../images/fashion-img(8)(4).png"
import drive_1 from "../images/fashion-img(9).png"
import drive_2 from "../images/fashion-img(9)(2).png"
import drive_3 from "../images/fashion-img(9)(3).png"
import drive_4 from "../images/fashion-img(9)(4).png"
import thermostat_1 from "../images/fashion-img(10).png"
import thermostat_2 from "../images/fashion-img(10)(2).png"
import thermostat_3 from "../images/fashion-img(10)(3).png"
import necklace_1 from "../images/fashion-img(11).png"
import necklace_2 from "../images/fashion-img(11)(2).png"
import necklace_3 from "../images/fashion-img(11)(3).png"
import necklace_4 from "../images/fashion-img(11)(4).png"
import cup_1 from "../images/fashion-img(12).png"
import cup_2 from "../images/fashion-img(12)(2).png"
import cup_3 from "../images/fashion-img(12)(3).png"
import cup_4 from "../images/fashion-img(12)(4).png"
import alcohol from "../images/fashion-img(13).png"
import flowerpot from "../images/fashion-img(14).png"
import Planer_1 from "../images/fashion-img(15).png"
import Planer_2 from "../images/fashion-img(15)(2).png"
import Planer_3 from "../images/fashion-img(15)(3).png"
import Planer_4 from "../images/fashion-img(15)(4).png"
import bag_1 from "../images/fashion-img(16).png"
import bag_2 from "../images/fashion-img(16)(2).png"
import bag_3 from "../images/fashion-img(16)(3).png"
import bag_4 from "../images/fashion-img(16)(4).png"

const products = [
	{
		id: 1,
		brand: "Droopier",
		title: "Regular Cotton T-Shirt",
		oldPrice: 24,
		price: 14,
		rating: 5,
		ratingIndex: 49903,
		sku: "CB-650490",
		gender: "male",
		category: "T-Shirts",
		color: ["#000", "#44506A", "#DC2626", "#F97316"],
		material: "Cotton Blend",
		occasion: "Casual",
		discount: "30% or more",
		badge: "TOP RATED",
		badgeColor: "#DC2626",
		badgeImage: null,
		defaultColorIndex: 2,
		variants: [
			{ color: "#000", image: tshirt_black, colorName: "Black" },
			{ color: "#44506A", image: tshirt_blue, colorName: "Blue" },
			{ color: "#DC2626", image: tshirt_red, colorName: "Red" },
			{ color: "#F97316", image: tshirt_yellow, colorName: "Yellow" },
		],
	},
	{
		id: 2,
		brand: "Nike",
		title: "SB Ishod Wair Wheat Flax DC7232-200",
		oldPrice: 156,
		price: 119,
		rating: 4,
		ratingIndex: 202,
		sku: "CB-650490",
		gender: "female",
		category: "Formal Shoes",
		color: ["#000", "#44506A", "#F59E0B", "#F97316"],
		material: "Organic Cotton",
		occasion: "Sports",
		discount: "60% or more",
		badge: "BEST SELLER",
		badgeColor: "#1E40AF",
		badgeImage: null,
		defaultColorIndex: 2,
		variants: [
			{ color: "#000", image: shoes_black, colorName: "Black" },
			{ color: "#44506A", image: shoes_blue, colorName: "Blue" },
			{ color: "#F59E0B", image: shoes_yellow, colorName: "Yellow" },
			{ color: "#F97316", image: shoes_orange, colorName: "Orange" },
		],
	},
	{
		id: 3,
		brand: "CoralBay",
		title: "Minimalist Black Wooden Stool - Modern Home Furniture",
		oldPrice: 69,
		price: 49,
		rating: 3,
		ratingIndex: 4787,
		sku: "CB-650490",
		gender: "kids",
		category: "Casual Trousers",
		color: ["#0A0E17", "#16A34A", "#FFFFFF", "#6C5E51"],
		material: "Wool Blend",
		occasion: "Festive",
		discount: "70% or more",
		badge: "BEST DEAL",
		badgeColor: "#F59E0B",
		badgeImage: null,
		defaultColorIndex: 0,
		variants: [
			{ color: "#0A0E17", image: stool_black, colorName: "Black" },
			{ color: "#16A34A", image: stool_green, colorName: "Green" },
			{ color: "#FFFFFF", image: stool_white, colorName: "White" },
			{ color: "#6C5E51", image: stool_grey, colorName: "Grey" },
		],
	},
	{
		id: 4,
		brand: "Polo Ralph Lauren",
		title: "Premium Tasselled Leather Loafers – Formal Men’s Footwear",
		oldPrice: 1499,
		price: 1349,
		rating: 5,
		ratingIndex: 6,
		sku: "CB-650490",
		gender: "female",
		category: "Sports Shoes",
		color: ["#000", "#44506A", "#F59E0B", "#F97316"],
		material: "Modal",
		occasion: "Sports",
		discount: "50% or more",
		badge: null,
		badgeColor: "#F97316",
		badgeImage: bagde_logo,
		defaultColorIndex: 2,
		variants: [
			{ color: "#000", image: shoes2_black, colorName: "Black" },
			{ color: "#44506A", image: shoes2_grey, colorName: "Grey" },
			{ color: "#F59E0B", image: shoes2_yellow, colorName: "Yellow" },
			{ color: "#F97316", image: shoes2_orange, colorName: "Orange" },
		]
	},
	{
		id: 5,
		brand: "Stockmart",
		title: "Summit Rooftop Cargo Carrier for SUV",
		oldPrice: 1499,
		price: 949,
		rating: "3",
		ratingIndex: "48",
		sku: "CB-650490",
		gender: "male",
		category: "Track Pants & Joggers",
		color: ["#0A0E17", "#16A34A", "#44506A", "#6C5E51"],
		material: "Viscose Rayon",
		occasion: "Beach Wear",
		discount: "30% or more",
		badge: "NEW",
		badgeColor: "#2563EB",
		badgeImage: null,
		defaultColorIndex: 0,
		variants: [
			{ color: "#0A0E17", image: stockmart_black, colorName: "Black" },
			{ color: "#16A34A", image: stockmart_green, colorName: "Green" },
			{ color: "#44506A", image: stockmart_blue, colorName: "Blue" },
			{ color: "#6C5E51", image: stockmart_brown, colorName: "Brown" },
		],
	},
	{
		id: 6,
		brand: "Digital Electric",
		title: "WD19 180W Docking Station",
		oldPrice: 119,
		price: 99,
		rating: 5,
		ratingIndex: 1844,
		sku: "CB-650490",
		gender: "female",
		category: "Watches",
		color: ["#0A0E17", "#44506A", "#BABABA"],
		material: "Polyester",
		occasion: "Lounge Wear",
		discount: "40% or more",
		badge: "TRENDING",
		badgeColor: "#16A34A",
		badgeImage: null,
		defaultColorIndex: 2,
		variants: [
			{ color: "#0A0E17", image: digital_3, colorName: "Black" },
			{ color: "#44506A", image: digital_2, colorName: "Blue" },
			{ color: "#BABABA", image: digital_1, colorName: "Grey" },
		],
	},
	{
		id: 7,
		brand: "Playground",
		title: "Bunny Hill Musical Toy",
		oldPrice: 19,
		price: 12,
		rating: 3,
		ratingIndex: 677,
		sku: "CB-650490",
		gender: "kids",
		category: "Shots",
		color: ["#000", "#44506A", "#F59E0B", "#F97316"],
		material: "Elastane",
		occasion: "Party",
		discount: "70% or more",
		badge: null,
		badgeColor: "",
		badgeImage: null,
		defaultColorIndex: 2,
		variants: [
			{ color: "#000", image: bunny_toy_2, colorName: "Black" },
			{ color: "#44506A", image: bunny_toy_3, colorName: "Blue" },
			{ color: "#F59E0B", image: bunny_toy_1, colorName: "Yellow" },
			{ color: "#F97316", image: bunny_toy_4, colorName: "Orange" },
		],
	},
	{
		id: 8,
		brand: "Arnold Tech",
		title: "MagSafe Charger with Stand and Ring",
		oldPrice: 99,
		price: 79,
		rating: 4,
		ratingIndex: 22354,
		sku: "CB-650490",
		gender: "unisex",
		category: "Sneakers",
		color: ["#000", "#44506A", "#1E40AF", "#F97316"],
		material: "Organic Cotton",
		occasion: "Formal",
		discount: "30% or more",
		badge: null,
		badgeColor: "",
		badgeImage: null,
		defaultColorIndex: 2,
		variants: [
			{ color: "#000", image: battery_4, colorName: "Black" },
			{ color: "#44506A", image: battery_2, colorName: "Grey" },
			{ color: "#1E40AF", image: battery_1, colorName: "Blue" },
			{ color: "#F97316", image: battery_3, colorName: "Orange" },
		],
	},
	{
		id: 9,
		brand: "Acme Enterprise",
		title: "SanDisk extreme portable SSD drive",
		oldPrice: 845,
		price: 745,
		rating: 5,
		ratingIndex: 3,
		sku: "CB-650490",
		gender: "unisex",
		category: "Blazer & Coats",
		color: ["#0A0E17", "#44506A", "#DC2626", "#F97316"],
		material: "Nylon",
		occasion: "Formal",
		discount: "50% or more",
		badge: "",
		badgeColor: "",
		badgeImage: null,
		defaultColorIndex: 3,
		variants: [
			{ color: "#0A0E17", image: drive_2, colorName: "Black" },
			{ color: "#44506A", image: drive_3, colorName: "Grey" },
			{ color: "#DC2626", image: drive_4, colorName: "Red" },
			{ color: "#F97316", image: drive_1, colorName: "Orange" },
		],
	},
	{
		id: 10,
		brand: "Hurry Technology",
		title: "Google nest learning thermostat",
		oldPrice: 445,
		price: 429,
		rating: 4,
		ratingIndex: 18,
		sku: "CB-650490",
		gender: "male",
		category: "Jeans",
		color: ["#0A0E17", "#1E40AF", "#D1D5DB"],
		material: "Pure Cotton",
		occasion: "Sports",
		discount: "60% or more",
		badge: "",
		badgeColor: "",
		badgeImage: null,
		defaultColorIndex: 0,
		variants: [
			{ color: "#0A0E17", image: thermostat_1, colorName: "Black" },
			{ color: "#1E40AF", image: thermostat_2, colorName: "Blue" },
			{ color: "#D1D5DB", image: thermostat_3, colorName: "Grey" },
		],
	},
	{
		id: 11,
		brand: "GGD Jewells",
		title: "The Megan Pendant 18K Gold with Pearl",
		oldPrice: 169,
		price: 149,
		rating: 5,
		ratingIndex: 6,
		sku: "CB-650490",
		gender: "female",
		category: "Casual Trousers",
		color: ["#000", "#44506A", "#F59E0B", "#F97316"],
		material: "Viscose Rayon",
		occasion: "Casual",
		discount: "40% or more",
		badge: null,
		badgeColor: "",
		badgeImage: null,
		defaultColorIndex: 2,
		variants: [
			{ color: "#000", image: necklace_3, colorName: "Black" },
			{ color: "#44506A", image: necklace_2, colorName: "Grey" },
			{ color: "#F59E0B", image: necklace_1, colorName: "Yellow" },
			{ color: "#F97316", image: necklace_4, colorName: "Orange" },
		],
	},
	{
		id: 12,
		brand: "Daycare",
		title: "Kid’s Training Cup",
		oldPrice: 21,
		price: 11,
		rating: 5,
		ratingIndex: 42,
		sku: "CB-650490",
		gender: "kids",
		category: "Socks",
		color: ["#0A0E17", "#16A34A", "#FFFFFF", "#6C5E51"],
		material: "Linen Blend",
		occasion: "Festive",
		discount: "50% or more",
		badge: "NEW",
		badgeColor: "#2563EB",
		badgeImage: null,
		defaultColorIndex: 1,
		variants: [
			{ color: "#0A0E17", image: cup_2, colorName: "Black" },
			{ color: "#16A34A", image: cup_1, colorName: "Green" },
			{ color: "#FFFFFF", image: cup_3, colorName: "White" },
			{ color: "#6C5E51", image: cup_4, colorName: "Brown" },
		],
	},
	{
		id: 13,
		brand: "Baume.be",
		title: "Aftershave Balm - 100ml Alcohol free",
		oldPrice: 99,
		price: 89,
		rating: 5,
		ratingIndex: 22489,
		sku: "CB-650490",
		gender: "male",
		category: "Jackets",
		color: ["#000", "#44506A", "#DC2626", "#F97316"],
		material: "Poly Cotton",
		occasion: "Formal",
		discount: "70% or more",
		badge: "",
		badgeColor: "",
		badgeImage: null,
		defaultColorIndex: 0,
		variants: [
			{ color: "#", image: alcohol },
		],
	},
	{
		id: 14,
		brand: "Urban Floralis",
		title: "Parlor Palm (Chamaedorea elegans)",
		oldPrice: 59,
		price: 29,
		rating: 4,
		ratingIndex: 10001,
		sku: "CB-650490",
		gender: "female",
		category: "Sports Shoes",
		color: ["#000", "#44506A", "#DC2626", "#F97316"],
		material: "Cotton Blend",
		occasion: "Party",
		discount: "50% or more",
		badge: "TOP RATED",
		badgeColor: "#DC2626",
		badgeImage: null,
		defaultColorIndex: 0,
		variants: [
			{ color: "#", image: flowerpot },
		],
	},
	{
		id: 15,
		brand: "Helenus Tools",
		title: "10-750 Electric Hand Planer DIY Planer Electric (750 W, Plane Width 82 mm, Chip Depth 0-3.0 mm, Folding Depth 0-15 mm)",
		oldPrice: 319,
		price: 219,
		rating: 5,
		ratingIndex: 6349,
		sku: "CB-650490",
		gender: "kids",
		category: "Sneakers",
		color: ["#0A0E17", "#44506A", "#F59E0B", "#F97316"],
		material: "Organic Cotton",
		occasion: "Sports",
		discount: "30% or more",
		badge: "",
		badgeColor: "",
		badgeImage: null,
		defaultColorIndex: 2,
		variants: [
			{ color: "#0A0E17", image: Planer_3, colorName: "Black" },
			{ color: "#44506A", image: Planer_2, colorName: "Green" },
			{ color: "#F59E0B", image: Planer_1, colorName: "White" },
			{ color: "#F97316", image: Planer_4, colorName: "Brown" },
		],
	},
	{
		id: 16,
		brand: "Grog Bags",
		title: "Helix - A New Kind of Lather Bag with Adjustable band",
		oldPrice: 999,
		price: 997,
		rating: 5,
		ratingIndex: 6789,
		sku: "CB-650490",
		gender: "female",
		category: "Casual Shirts",
		color: ["#B000B9", "#F59E0B", "#00FFE1", "#FF6565"],
		material: "Elastane",
		occasion: "Festive",
		discount: "40% or more",
		badge: "",
		badgeColor: "",
		badgeImage: null,
		defaultColorIndex: 1,
		variants: [
			{ color: "#B000B9", image: bag_2 },
			{ color: "#F59E0B", image: bag_1 },
			{ color: "#00FFE1", image: bag_3 },
			{ color: "#FF6565", image: bag_4 },
		],
	},
	{
		id: 17,
		brand: "Droopier",
		title: "Regular Cotton T-Shirt",
		oldPrice: 24,
		price: 14,
		rating: 5,
		ratingIndex: 49903,
		sku: "CB-650490",
		gender: "male",
		category: "T-Shirts",
		color: ["#000", "#44506A", "#DC2626", "#F97316"],
		material: "Cotton Blend",
		occasion: "Casual",
		discount: "30% or more",
		badge: null,
		badgeColor: "#F97316",
		badgeImage: bagde_logo,
		defaultColorIndex: 1,
		variants: [
			{ color: "#000", image: tshirt_black, colorName: "Purple" },
			{ color: "#44506A", image: tshirt_blue, colorName: "Yellow" },
			{ color: "#DC2626", image: tshirt_red, colorName: "Sky blue" },
			{ color: "#F97316", image: tshirt_yellow, colorName: "Pink" },
		],
	},
];

export default products;
